### ISSUE TITLE
Increase width of popup

### ISSUE THREAD

**Issue by dbhirko** [sadovnychyi/autocomplete-python#122]
Is there a way to increase the width of the autocomplete popup window?  Love the package as it is very helpful.

**Comment by sadovnychyi** [comment]
Why do you want to increase it?

You could add something like 
```css
autocomplete-suggestion-list.select-list.popover-list {
  width: 100px !important; // to override inline styles
  max-width: 800px; // the default one.
}
```
intro your styles.less.
