### ISSUE TITLE
Show docstring in right instead of bottom of context menu

### ISSUE THREAD

**Issue by zardav** [sadovnychyi/autocomplete-python#206]
Hi.
Is it possible to open the docstring in right of the context menu instead of bottom?
Also if it is possible to make it scrollable it will be very good.

**Comment by sadovnychyi** [comment]
You can make it smaller and scrollable by editing your styles.less by adding something like:

```less
atom-text-editor[data-grammar="source python"], :host {
  .autocomplete-suggestion-list.select-list.popover-list .suggestion-description {
    max-height: 5em;
    overflow: auto;
  }
}
```

I think you could move it to the right by editing CSS as well.

This is related to autocomplete-plus, so I don't think that it's a good idea to change it in this repo.
